const FETCH_FEATURED_QUESTIONS = "FETCH_FEATURED_QUESTIONS";
const FETCH_USERDATA = "FETCH_USERDATA";
const FETCH_USER_QUESTIONS = "FETCH_USER_QUESTIONS";
const FETCH_USERTAGS = "FETCH_USERTAGS";
const FETCH_START = "FETCH_START";

export {FETCH_FEATURED_QUESTIONS, FETCH_START, FETCH_USERDATA, FETCH_USER_QUESTIONS, FETCH_USERTAGS};